# Generated by Django 4.2.5 on 2023-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignupData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("license_number", models.CharField(max_length=50)),
                ("license_exp", models.DateField()),
                ("payment_info", models.CharField(max_length=100)),
            ],
        ),
    ]
